---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-ovh
  namespace: cert-manager
spec:
  interval: 30m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      chart: cert-manager-webhook-ovh
      version: "0.6.x"
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-ovh
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    groupName: acme.cert-manager.io
