apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umami-db-data
  namespace: monitoring-prd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
