apiVersion: v1
kind: Service
metadata:
  name: trading-simulator
  namespace: cv-site-prd
  labels:
    app: trading-simulator
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: trading-simulator
