apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-domain-tls
  namespace: cv-site-prd
spec:
  secretName: root-domain-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - sebastien.sh
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-tls
  namespace: cv-site-prd
spec:
  secretName: frontend-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - cv.sebastien.sh
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-tls
  namespace: cv-site-prd
spec:
  secretName: api-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - api.sebastien.sh
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authelia-tls
  namespace: authelia
spec:
  secretName: authelia-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - auth.sebastien.sh
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: monitoring-prd
spec:
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - grafana.sebastien.sh
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: akhq-tls
  namespace: monitoring-prd
spec:
  secretName: akhq-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - akhq.sebastien.sh
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls
  namespace: monitoring-prd
spec:
  secretName: prometheus-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - prometheus.sebastien.sh
