---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: authelia
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authelia-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/cv-site/authelia
        property: jwt-secret
    - secretKey: SESSION_SECRET
      remoteRef:
        key: secret/cv-site/authelia
        property: session-secret
    - secretKey: STORAGE_ENCRYPTION_KEY
      remoteRef:
        key: secret/cv-site/authelia
        property: storage-encryption-key
    - secretKey: users_database.yml
      remoteRef:
        key: secret/cv-site/authelia
        property: users-database
